runFrom: 1 #номер первой симуляций
runNum: 100 #число симуляций
L0: 3 #радиус обрезания
timeStep: 0.02 #шаг времени
timeIni: 10000 #время подготовки стартового состояния
Fs: 0.2 #нормировка суммы сил при возбуждении
timeLimit: 1000000 #максимальное число шагов моделирования 
nodes: #узлы сети
  -
    - 29.071289
    - 12.112305 
    - 44.331055 
  - 
    - 29.071289 
    - 12.112305 
    - 44.331055 
  - 
    - 29.071289 
    - 12.112305 
    - 43.331055 
activeNodes: #узлы к которым прикладывается сила при возбуждении. Если этот параметр не задан - сила прикладывается ко всем узлам 
  - 1 
  - 2 
visualizationNodes: #узлы, используемые при построении релаксационных траекторий 
  - 3 
  - 1 
  - 2
