Fs: 2
timeStep: 0.02
timeIni: 10000
runNum: 100
activeNodes:
  - 1
  - 3
visualizationNodes:
  - 0
  - 2
nodes:
  -
    - 29.1
    - 11.3
    - 73.2
  -
    - 57.2
    - 20.8
    - 54.4
  -
    - 37.6
    - 17.8
    - 23.0
  -
    - 45.1
    - 99.9
    - 16.2
links:
  -
    - 3
    - 1
  -
    - 1
    - 2
