runNum: 100 #число симуляций
timeStep: 0.02 #шаг времени
timeIni: 10000 #время подготовки стартового состояния
Fs: 0.2 #нормировка суммы сил при возбуждении
L0: 3
forcesDynamic: false
networkFile: "hier_potential.yaml"
