runNum: 10 #число симуляций
timeStep: 0.02 #шаг времени
timeIni: 10000 #время подготовки стартового состояния
Fs: 0.2 #нормировка суммы сил при возбуждении
timeLimit: 1000000 #максимальное число шагов моделирования 
L0: 3
networkFile: !!str hier_potential.yaml
