runNum: 100 #число симуляций
timeStep: 0.02 #шаг времени
timeIni: 100000 #время подготовки стартового состояния
Fs: 0.2 #нормировка суммы сил при возбуждении
timeLimit: 10000000 #максимальное число шагов моделирования 
L0: 3
networkFile: "hier_potential.yaml"
