resultsDir: "results"
generationDir: "generation"
excitationFileName: "excitation.txt"
relaxationFileName: "relaxation.txt"
trajectoryFileName: "trajectory.txt"
eigensFileName: "eigens.txt"
nodesFileName: "nodes.txt"
dumpData: false
dumpStep: 10
timeLimit: 10000000 #максимальное число шагов моделирования
stabilizationEpsilon: 1e-9
stabilizationSteps: 10000
