resultsDir: "results"
generationDir: "generation"
excitationFileName: "excitation.txt"
relaxationFileName: "relaxation.txt"
trajectoryFileName: "trajectory.txt"
eigensFileName: "eigens.txt"
nodesFileName: "nodes.txt"
dumpStep: 10
