resultsDir: !!str results
generationDir: !!str generation
excitationFileName: !!str excitation.txt
relaxationFileName: !!str relaxation.txt
trajectoryFileName: !!str trajectory.txt
eigensFileName: !!str eigens.txt
nodesFileName: !!str nodes.txt
dumpStep: 10
