resultsDir: "results"
generationDir: "generation"
excitationFileName: "excitation.txt"
relaxationFileName: "relaxation.txt"
trajectoryFileName: "trajectory.txt"
eigensFileName: "eigens.txt"
nodesFileName: "nodes.txt"
dumpData: false
dumpStep: 10
relaxationTimeLimit: 10000000 #максимальное число шагов моделирования
stabilizationSpec:
  epsilon: 5e-2
  stepCount: 1000
